-- USUARIO ADMIN
-- CASO 1

SHOW USER;

-- CREACIÓN DE USUARIOS

-- USUARIO DUEÑO (OWNER)
CREATE USER PRY2205_EFT
IDENTIFIED BY "Ab12CD3456ef"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON DATA;

-- USUARIO GENERICO (DESARROLLADOR)
CREATE USER PRY2205_EFT_DES
IDENTIFIED BY "AsdfgH123456"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON DATA;

-- USUARIO GENERICO
CREATE USER PRY2205_EFT_CON
IDENTIFIED BY "ZxcvbN123456"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA 10M ON DATA;


-- CREACION DE ROLES

DROP ROLE PRY2205_ROL_D;

CREATE ROLE PRY2205_ROL_D;
CREATE ROLE PRY2205_ROL_C;

-- ASIGNACION DE ROLES

GRANT PRY2205_ROL_D TO PRY2205_EFT_DES;
GRANT PRY2205_ROL_C TO PRY2205_EFT_CON;


-- PRIVILEGIOS DE SISTEMA

-- USUARIO DUEÑO (OWNER)
GRANT CREATE SESSION TO PRY2205_EFT;
GRANT CREATE TABLE TO PRY2205_EFT; 
GRANT CREATE VIEW TO PRY2205_EFT;
GRANT CREATE SEQUENCE TO PRY2205_EFT;
GRANT CREATE SYNONYM TO PRY2205_EFT; 
GRANT CREATE PUBLIC SYNONYM TO PRY2205_EFT;

-- USUARIO GENERICO (DESARROLLADOR)
GRANT CREATE SESSION TO PRY2205_EFT_DES;
GRANT CREATE TABLE TO PRY2205_EFT_DES;
GRANT CREATE VIEW TO PRY2205_EFT_DES;
GRANT CREATE PROFILE TO PRY2205_EFT_DES; 
GRANT CREATE USER TO PRY2205_EFT_DES;

-- USUARIO GENERICO
GRANT CREATE SESSION TO PRY2205_EFT_CON;

------------------------------------------------------------------------------------------------
-- USUARIO: PRY2205_EFT
-- CASO 1
-- ASIGNACIÓN DE ACCESOS Y SINÓNIMOS

SHOW USER;

-- PRIVILEGIOS ROLES

GRANT SELECT ON PROFESIONAL    TO PRY2205_ROL_D;
GRANT SELECT ON PROFESION      TO PRY2205_ROL_D;
GRANT SELECT ON COMUNA         TO PRY2205_ROL_D;
GRANT SELECT ON TIPO_CONTRATO  TO PRY2205_ROL_D;
GRANT SELECT ON ISAPRE         TO PRY2205_ROL_D;
GRANT SELECT ON RANGOS_SUELDOS TO PRY2205_ROL_D;

GRANT SELECT ON PROFESIONAL   TO PRY2205_ROL_C;
GRANT SELECT ON PROFESION     TO PRY2205_ROL_C;
GRANT SELECT ON COMUNA        TO PRY2205_ROL_C;
GRANT SELECT ON TIPO_CONTRATO TO PRY2205_ROL_C;

-- CREACIÓN DE SINÓNIMOS PÚBLICOS

CREATE PUBLIC SYNONYM SYN_PROFESIONAL
FOR PRY2205_EFT.PROFESIONAL;

CREATE PUBLIC SYNONYM SYN_PROFESION
FOR PRY2205_EFT.PROFESION;

CREATE PUBLIC SYNONYM SYN_COMUNA
FOR PRY2205_EFT.COMUNA;

CREATE PUBLIC SYNONYM SYN_TIPO_CONTRATO
FOR PRY2205_EFT.TIPO_CONTRATO;

CREATE PUBLIC SYNONYM SYN_ISAPRE
FOR PRY2205_EFT.ISAPRE;

CREATE PUBLIC SYNONYM SYN_RANGOS_SUELDOS
FOR PRY2205_EFT.RANGOS_SUELDOS;

CREATE PUBLIC SYNONYM SYN_EMPRESA  FOR PRY2205_EFT.EMPRESA;
CREATE PUBLIC SYNONYM SYN_ASESORIA FOR PRY2205_EFT.ASESORIA;

-- SINÓNIMO PRIVADO (USO INTERNO)

CREATE SYNONYM MI_PROFESIONAL
FOR PRY2205_EFT.PROFESIONAL;


--CASO 3.1 - CREACIÓN VISTA EMPRESAS ASESORADAS
--USUARIO PRY2205_EFT (OWNER)

-- CREACIÓN DE LA VISTA

SHOW USER;

CREATE OR REPLACE VIEW VW_EMPRESAS_ASESORADAS AS
SELECT
    e.rut_empresa || '-' || e.dv_empresa                AS RUT_EMPRESA,

    UPPER(e.nomempresa)                                 AS NOMBRE_EMPRESA,

    e.iva_declarado                                     AS IVA,

    EXTRACT(YEAR FROM SYSDATE) - EXTRACT(YEAR FROM e.fecha_iniciacion_actividades) AS ANIOS_EXISTENCIA,

    TRUNC(COUNT(*) / 12)                                AS TOTAL_ASESORIAS_ANUALES,

    TRUNC(
        e.iva_declarado * TRUNC(COUNT(*) / 12) / 100
    )                                                   AS DEVOLUCION_IVA,

    CASE
        WHEN TRUNC(COUNT(*) / 12) > 5
            THEN 'CLIENTE PREMIUM'
        WHEN TRUNC(COUNT(*) / 12) BETWEEN 3 AND 5
            THEN 'CLIENTE'
        ELSE 'CLIENTE POCO CONCURRIDO'
    END                                                 AS TIPO_CLIENTE,
    CASE
        WHEN TRUNC(COUNT(*) / 12) > 5 AND COUNT(*) >= 7
            THEN '1 ASESORIA GRATIS'

        WHEN TRUNC(COUNT(*) / 12) > 5 AND COUNT(*) < 7
            THEN '1 ASESORIA 40% DE DESCUENTO'

        WHEN TRUNC(COUNT(*) / 12) BETWEEN 3 AND 5 AND COUNT(*) = 5
            THEN '1 ASESORIA 30% DE DESCUENTO'

        WHEN TRUNC(COUNT(*) / 12) BETWEEN 3 AND 5 AND COUNT(*) < 5
            THEN '1 ASESORIA 20% DE DESCUENTO'

        ELSE 'CAPTAR CLIENTE'
    END                                                 AS CORRESPONDE

FROM
    SYN_EMPRESA e
    JOIN SYN_ASESORIA a
        ON e.idempresa = a.idempresa

WHERE
    EXTRACT(YEAR FROM a.fin) = EXTRACT(YEAR FROM SYSDATE) - 1

GROUP BY
    e.rut_empresa,
    e.dv_empresa,
    e.nomempresa,
    e.iva_declarado,
    e.fecha_iniciacion_actividades

ORDER BY
    NOMBRE_EMPRESA ASC;

-- PERMISO PARA PRY2205_EFT_CON
GRANT SELECT ON VW_EMPRESAS_ASESORADAS TO PRY2205_EFT_CON;



--   CASO 2 
--   Usuario PRY2205_EFT_DES

SHOW USER;


-- CREACIÓN DE LA TABLA CARTOLA_PROFESIONALES


CREATE TABLE CARTOLA_PROFESIONALES AS
SELECT
    p.rutprof AS RUT_PROFESIONAL,

    INITCAP(p.nompro || ' ' ||
            p.apppro || ' ' ||
            p.apmpro) AS NOMBRE_PROFESIONAL,

    INITCAP(pr.nomprofesion) AS PROFESION,

    INITCAP(i.nomisapre) AS ISAPRE,

    p.sueldo AS SUELDO_BASE,

    NVL(p.comision, 0) AS PORC_COMISION_PROFESIONAL,

    ROUND(p.sueldo * NVL(p.comision, 0)) AS VALOR_TOTAL_COMISION,

    ROUND(p.sueldo * (rs.honor_pct / 100)) AS PORCENTAJE_HONORARIO,

    CASE
        WHEN tc.nomtcontrato = 'Indefinido Jornada Completa' THEN 150000
        WHEN tc.nomtcontrato = 'Indefinido Jornada Parcial'  THEN 120000
        WHEN tc.nomtcontrato = 'Plazo fijo'                  THEN 60000
        WHEN tc.nomtcontrato = 'Honorarios'                  THEN 50000
        ELSE 0
    END AS BONO_MOVILIZACION,

    ROUND(
        p.sueldo
        + (p.sueldo * NVL(p.comision, 0))
        + (p.sueldo * (rs.honor_pct / 100))
        + CASE
            WHEN tc.nomtcontrato = 'Indefinido Jornada Completa' THEN 150000
            WHEN tc.nomtcontrato = 'Indefinido Jornada Parcial'  THEN 120000
            WHEN tc.nomtcontrato = 'Plazo fijo'                  THEN 60000
            WHEN tc.nomtcontrato = 'Honorarios'                  THEN 50000
            ELSE 0
        END
    ) AS TOTAL_PAGAR


FROM
    SYN_PROFESIONAL p

    INNER JOIN SYN_PROFESION pr
        ON p.idprofesion = pr.idprofesion

    LEFT JOIN SYN_ISAPRE i
        ON p.idisapre = i.idisapre

    INNER JOIN SYN_TIPO_CONTRATO tc
        ON p.idtcontrato = tc.idtcontrato

    INNER JOIN SYN_RANGOS_SUELDOS rs
        ON p.sueldo BETWEEN rs.s_min AND rs.s_max;

-- INFORME
SELECT * FROM CARTOLA_PROFESIONALES;    

-- Usuario PRY2205_EFT_CON
-- CASO 3.1

SHOW USER;
SELECT * FROM PRY2205_EFT.VW_EMPRESAS_ASESORADAS;
