-- USUARIO ADMIN 
-- CASO 1
-- CREACION USUARIO OWNER (DUEÑO) - PRY2205_USER1
CREATE USER PRY2205_USER1
IDENTIFIED BY "ClaveActividadSumativa3"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DATA;

CREATE USER PRY2205_USER2
IDENTIFIED BY "ClaveActividadSumativa3"
DEFAULT TABLESPACE DATA
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON DATA;

GRANT CREATE SESSION TO PRY2205_USER1;
GRANT CREATE SESSION TO PRY2205_USER2;

-- CREACION DE ROLES
-- ROL DUEÑO - PRY2205_ROL_D
CREATE ROLE PRY2205_ROL_D;
GRANT CREATE TABLE TO PRY2205_ROL_D;
GRANT CREATE VIEW TO PRY2205_ROL_D;
GRANT CREATE SYNONYM TO PRY2205_ROL_D;
GRANT CREATE PUBLIC SYNONYM TO PRY2205_ROL_D;

-- ROL GENERICO - PRY2205_ROL_P
CREATE ROLE PRY2205_ROL_P;
GRANT CREATE TABLE TO PRY2205_ROL_P;
GRANT CREATE SEQUENCE TO PRY2205_ROL_P;
GRANT CREATE TRIGGER TO PRY2205_ROL_P;

-- ASIGNACION DE ROLES A USUARIOS
GRANT PRY2205_ROL_D TO PRY2205_USER1;
GRANT PRY2205_ROL_P TO PRY2205_USER2;

-- PRIVILEGIOS
-- PARA QUE PRY2205_USER2 PUEDA TRABAJAR CON TABLAS
GRANT SELECT ON PRY2205_USER1.LIBRO TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.EJEMPLAR TO PRY2205_ROL_P;
GRANT SELECT ON PRY2205_USER1.PRESTAMO TO PRY2205_ROL_P;

--==========================================================================================================================================================

-- USUARIO OWNER (DUEÑO) - PRY2205_USER1

-- ACA SE HIZO LA CREACION DE TABLAS Y POBLAMIENTO (CODIGO ENTREGADO EN LAS INSTRUCCIONES)

DROP SYNONYM SINONIMO_LIBRO;
DROP VIEW VW_DETALLE_MULTAS;
DROP INDEX INDICE_PRESTAMO_ANIO;

-- CASO 1
-- CREACION SINONIMO PRIVADO
CREATE SYNONYM SINONIMO_LIBRO FOR PRY2205_USER1.LIBRO;

-- CREACION SININOMOS PUBLICOS
CREATE PUBLIC SYNONYM LIBRO FOR PRY2205_USER1.LIBRO;
CREATE PUBLIC SYNONYM EJEMPLAR FOR PRY2205_USER1.EJEMPLAR;
CREATE PUBLIC SYNONYM PRESTAMO FOR PRY2205_USER1.PRESTAMO;

-- CASO 3.1
-- CREACION VISTA DETALLE MULTAS
CREATE OR REPLACE VIEW VW_DETALLE_MULTAS AS
SELECT
    p.prestamoid AS ID_PRESTAMO,
    a.nombre || ' ' || a.apaterno AS NOMBRE_ALUMNO,
    c.descripcion AS NOMBRE_CARRERA,
    l.libroid AS ID_LIBRO,
    TO_CHAR(l.precio, '$9G999G999') AS VALOR_LIBRO,
    TO_CHAR(p.fecha_termino, 'DD/MM/YYYY') AS FECHA_TERMINO,
    TO_CHAR(p.fecha_entrega, 'DD/MM/YYYY') AS FECHA_ENTREGA,
    (p.fecha_entrega - p.fecha_termino)              AS DIAS_ATRASO,
    TO_CHAR(ROUND(l.precio * 0.03 * (p.fecha_entrega - p.fecha_termino), 0),'$9G999G999') AS VALOR_MULTA,
    NVL(rm.porc_rebaja_multa, 0) / 100                AS PORCENTAJE_REBAJA_MULTA,
    TO_CHAR(ROUND((l.precio * 0.03 * (p.fecha_entrega - p.fecha_termino)) * (1 - NVL(rm.porc_rebaja_multa, 0) / 100),0),'$9G999G999') AS VALOR_REBAJADO
FROM prestamo p
    JOIN alumno a
        ON p.alumnoid = a.alumnoid
    JOIN carrera c
        ON a.carreraid = c.carreraid
    JOIN libro l
        ON p.libroid = l.libroid
    LEFT JOIN rebaja_multa rm
        ON c.carreraid = rm.carreraid   
WHERE
    p.fecha_entrega IS NOT NULL
    AND p.fecha_entrega > p.fecha_termino
    AND EXTRACT(YEAR FROM p.fecha_termino) = EXTRACT(YEAR FROM SYSDATE) - 2
ORDER BY
    p.fecha_entrega DESC;

--CASO 3.2
-- VISTA ANTES DE MEJORAR EL RENDIMIENTO CON EL INDICE
SELECT * FROM VW_DETALLE_MULTAS;

-- CREACION INDICE PARA MEJORAR RENDIMIENTO
CREATE INDEX INDICE_PRESTAMO_ANIO
ON PRESTAMO (EXTRACT(YEAR FROM fecha_termino));

-- VISTA DESPUES DE MEJORAR EL RENDIMIENTO CON EL INDICE
SELECT * FROM VW_DETALLE_MULTAS;

--==========================================================================================================================================================

-- USUARIO GENERICO - PRY2205_USER2
--CASO 2

DROP TABLE CONTROL_STOCK_LIBROS;
DROP SEQUENCE SEQ_CONTROL_STOCK;

-- CREACION DE OBJETO TABLA
CREATE TABLE CONTROL_STOCK_LIBROS AS
SELECT
    l.libroid AS LIBRO_ID,
    l.nombre_libro AS NOMBRE_LIBRO,
    COUNT(e.ejemplarid) AS TOTAL_EJEMPLARES,
    COUNT(p.prestamoid) AS EN_PRESTAMO,
    COUNT(e.ejemplarid) - COUNT(p.prestamoid) AS DISPONIBLES,
    ROUND(COUNT(p.prestamoid) / NULLIF(COUNT(e.ejemplarid), 0) * 100, 2) AS PORCENTAJE_PRESTAMO,
    CASE
        WHEN (COUNT(e.ejemplarid) - COUNT(p.prestamoid)) <= 1
        THEN 'S'
        ELSE 'N'
    END AS STOCK_CRITICO
FROM LIBRO l
    JOIN EJEMPLAR e
        ON l.libroid = e.libroid
    LEFT JOIN PRESTAMO p
        ON e.libroid     = p.libroid
        AND e.ejemplarid = p.ejemplarid
        AND EXTRACT(YEAR FROM p.fecha_inicio) = EXTRACT(YEAR FROM SYSDATE) - 2
        AND p.empleadoid IN (190, 180, 150)
GROUP BY
    l.libroid,
    l.nombre_libro
HAVING
    COUNT(p.prestamoid) > 0;

-- CREACION SECUENCIA
CREATE SEQUENCE SEQ_CONTROL_STOCK
START WITH 1
INCREMENT BY 1;

-- INFORME CASO 2
SELECT
    SEQ_CONTROL_STOCK.NEXTVAL AS ID_CONTROL,
    datos.LIBRO_ID,
    datos.NOMBRE_LIBRO,
    datos.TOTAL_EJEMPLARES,
    datos.EN_PRESTAMO,
    datos.DISPONIBLES,
    datos.PORCENTAJE_PRESTAMO,
    datos.STOCK_CRITICO
FROM (
    SELECT *
    FROM CONTROL_STOCK_LIBROS
    ORDER BY LIBRO_ID
) datos;